### ISSUE TITLE
Details view crashes

### ISSUE THREAD

**Issue by karlredman** [karlredman/Timetrap_TUI#1]
Details view crashes when invoked:
```
karl@scyld ~/Projects/github/Timetrap_TUI $ ./timetrap_tui.js
Error: watch /home/karl/Documents/Heorot/timetrap/timetrap.db ENOENT
    at FSWatcher.start (fs.js:1409:19)
    at Object.fs.watch (fs.js:1435:11)
    at Timetrap.monitorDBStart (/home/karl/Projects/github/Timetrap_TUI/node_modules/timetrap_wraplib/index.js:567:41)
    at new ViewDetails (/home/karl/Projects/github/Timetrap_TUI/lib/view_Details.js:56:23)
    at ViewController.on (/home/karl/Projects/github/Timetrap_TUI/lib/view_Controller.js:79:39)
    at ViewController.emit (events.js:180:13)
    at Object.Details [as callback] (/home/karl/Projects/github/Timetrap_TUI/lib/widget_Menubar.js:287:35)
    at Menubar.Listbar.selectTab (/home/karl/Projects/github/Timetrap_TUI/node_modules/blessed/lib/widgets/listbar.js:399:18)
    at Screen.<anonymous> (/home/karl/Projects/github/Timetrap_TUI/node_modules/blessed/lib/widgets/listbar.js:96:21)
    at Screen.EventEmitter._emit (/home/karl/Projects/github/Timetrap_TUI/node_modules/blessed/lib/events.js:94:20)

```

**Comment by karlredman** [comment]
fixed: had a hard coded path to the db in View_Details.js
